// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
    beginnerSidebar: [
        {
            type: "category",
            label: "新手指南",
            items: [
                "新手指南/新手指南入口",
                {
                    type: "autogenerated",
                    dirName: "新手指南",
                },
            ],
        },
    ],
    featureSidebar: [
        {
            type: "category",
            label: "功能文档",
            items: [
                "功能文档/功能文档入口",
                {
                    type: "autogenerated",
                    dirName: "功能文档",
                },
            ],
        },
    ],
    devSidebar: [
        {
            type: "category",
            label: "开发文档",
            items: [
                "开发者文档/开发者文档入口",
                "开发者文档/快速开始",
                "开发者文档/个性化配置",
                "开发者文档/文档编写规范",
                "开发者文档/文档维护流程",
                {
                    type: "autogenerated",
                    dirName: "开发者文档",
                },
            ],
        },
    ],
    aboutSidebar: [
        {
            type: "category",
            label: "关于我们",
            items: [
                {
                    type: "autogenerated",
                    dirName: "关于",
                },
            ],
        },
    ],
};

export default sidebars;
