// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
    beginnerSidebar: [
        {
            type: "category",
            label: "新手指南",
            items: [
                "新手指南/新手指南入口",
                "新手指南/环境准备",
                "新手指南/模拟器配置",
                "新手指南/连接程序与确认实例",
                "新手指南/开始任务",
                "新手指南/常见问题",
                "新手指南/AMD调优",
            ],
        },
    ],
    featureSidebar: [
        {
            type: "category",
            label: "功能文档",
            items: [
                "功能文档/功能文档入口",
                {
                    type: "category",
                    label: "按功能名查找",
                    items: [
                        {
                            type: "autogenerated",
                            dirName: "功能文档/自动钓鱼",
                        },
                        {
                            type: "autogenerated",
                            dirName: "功能文档/简易采集",
                        },
                        {
                            type: "autogenerated",
                            dirName: "功能文档/自动协会狩猎",
                        },
                        {
                            type: "autogenerated",
                            dirName: "功能文档/聊天频道发言",
                        },
                        {
                            type: "autogenerated",
                            dirName: "功能文档/游星岛环城载具赛",
                        },
                        {
                            type: "autogenerated",
                            dirName: "功能文档/S2自动刷茧",
                        },
                    ],
                },
            ],
        },
    ],
    devSidebar: [
        {
            type: "category",
            label: "开发文档",
            items: [
                "开发者文档/开发者文档入口",
                "开发者文档/快速开始",
                "开发者文档/个性化配置",
                "开发者文档/文档编写规范",
                "开发者文档/文档维护流程",
                "开发者文档/开发随笔",
                "开发者文档/待办清单",
                {
                    type: "autogenerated",
                    dirName: "开发者文档/流程设计",
                },
                {
                    type: "autogenerated",
                    dirName: "开发者文档/StarResonanceDamageCounter",
                },
            ],
        },
    ],
    aboutSidebar: [
        {
            type: "category",
            label: "关于我们",
            items: [
                {
                    type: "autogenerated",
                    dirName: "关于",
                },
            ],
        },
    ],
};

export default sidebars;
