# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent/utils/packet_capture/proto/attr.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agent/utils/packet_capture/proto/attr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+agent/utils/packet_capture/proto/attr.proto\x12\x06zproto\"@\n\x04\x41ttr\x12\x0f\n\x02Id\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x14\n\x07RawData\x18\x02 \x01(\x0cH\x01\x88\x01\x01\x42\x05\n\x03_IdB\n\n\x08_RawData\"I\n\x0e\x41ttrCollection\x12\x11\n\x04Uuid\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x1b\n\x05\x41ttrs\x18\x02 \x03(\x0b\x32\x0c.zproto.AttrB\x07\n\x05_Uuidb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent.utils.packet_capture.proto.attr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ATTR']._serialized_start=55
  _globals['_ATTR']._serialized_end=119
  _globals['_ATTRCOLLECTION']._serialized_start=121
  _globals['_ATTRCOLLECTION']._serialized_end=194
# @@protoc_insertion_point(module_scope)
