# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent/utils/packet_capture/proto/entity.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agent/utils/packet_capture/proto/entity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from agent.utils.packet_capture.proto import attr_pb2 as agent_dot_utils_dot_packet__capture_dot_proto_dot_attr__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-agent/utils/packet_capture/proto/entity.proto\x12\x06zproto\x1a+agent/utils/packet_capture/proto/attr.proto\"d\n\x06\x45ntity\x12\x0c\n\x04uuid\x18\x01 \x01(\x03\x12%\n\x08\x65nt_type\x18\x02 \x01(\x0e\x32\x13.zproto.EEntityType\x12%\n\x05\x61ttrs\x18\x03 \x01(\x0b\x32\x16.zproto.AttrCollection\"\x1f\n\x0f\x44isappearEntity\x12\x0c\n\x04uuid\x18\x01 \x01(\x03*\xc8\x02\n\x0b\x45\x45ntityType\x12\x0e\n\nEntErrType\x10\x00\x12\x0e\n\nEntMonster\x10\x01\x12\n\n\x06\x45ntNpc\x10\x02\x12\x12\n\x0e\x45ntSceneObject\x10\x03\x12\x0b\n\x07\x45ntZone\x10\x05\x12\r\n\tEntBullet\x10\x06\x12\x13\n\x0f\x45ntClientBullet\x10\x07\x12\n\n\x06\x45ntPet\x10\x08\x12\x0b\n\x07\x45ntChar\x10\n\x12\x0c\n\x08\x45ntDummy\x10\x0b\x12\x0b\n\x07\x45ntDrop\x10\x0c\x12\x0c\n\x08\x45ntField\x10\x0e\x12\x0b\n\x07\x45ntTrap\x10\x0f\x12\x11\n\rEntCollection\x10\x10\x12\x13\n\x0f\x45ntStaticObject\x10\x12\x12\x0e\n\nEntVehicle\x10\x13\x12\n\n\x06\x45ntToy\x10\x14\x12\x15\n\x11\x45ntCommunityHouse\x10\x15\x12\x10\n\x0c\x45ntHouseItem\x10\x16\x12\x0c\n\x08\x45ntCount\x10\x17\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent.utils.packet_capture.proto.entity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EENTITYTYPE']._serialized_start=238
  _globals['_EENTITYTYPE']._serialized_end=566
  _globals['_ENTITY']._serialized_start=102
  _globals['_ENTITY']._serialized_end=202
  _globals['_DISAPPEARENTITY']._serialized_start=204
  _globals['_DISAPPEARENTITY']._serialized_end=235
# @@protoc_insertion_point(module_scope)
