# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent/utils/packet_capture/proto/world_ntf.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agent/utils/packet_capture/proto/world_ntf.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from agent.utils.packet_capture.proto import attr_pb2 as agent_dot_utils_dot_packet__capture_dot_proto_dot_attr__pb2
from agent.utils.packet_capture.proto import entity_pb2 as agent_dot_utils_dot_packet__capture_dot_proto_dot_entity__pb2
from agent.utils.packet_capture.proto import char_data_pb2 as agent_dot_utils_dot_packet__capture_dot_proto_dot_char__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0agent/utils/packet_capture/proto/world_ntf.proto\x12\x06zproto\x1a+agent/utils/packet_capture/proto/attr.proto\x1a-agent/utils/packet_capture/proto/entity.proto\x1a\x30\x61gent/utils/packet_capture/proto/char_data.proto\"\xb9\x04\n\x08WorldNtf\x1a`\n\x0c\x41oiSyncDelta\x12\x11\n\x04Uuid\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12*\n\x05\x41ttrs\x18\x02 \x01(\x0b\x32\x16.zproto.AttrCollectionH\x01\x88\x01\x01\x42\x07\n\x05_UuidB\x08\n\x06_Attrs\x1as\n\x10\x41oiSyncToMeDelta\x12\x35\n\tBaseDelta\x18\x01 \x01(\x0b\x32\x1d.zproto.WorldNtf.AoiSyncDeltaH\x00\x88\x01\x01\x12\x11\n\x04Uuid\x18\x05 \x01(\x03H\x01\x88\x01\x01\x42\x0c\n\n_BaseDeltaB\x07\n\x05_Uuid\x1a:\n\x11SyncContainerData\x12%\n\x06v_data\x18\x01 \x01(\x0b\x32\x15.zproto.CharSerialize\x1a\'\n\x16SyncContainerDirtyData\x12\r\n\x05VData\x18\x01 \x01(\x0c\x1a\x46\n\x11SyncNearDeltaInfo\x12\x31\n\nDeltaInfos\x18\x01 \x03(\x0b\x32\x1d.zproto.WorldNtf.AoiSyncDelta\x1a^\n\x10SyncNearEntities\x12\x1e\n\x06\x61ppear\x18\x01 \x03(\x0b\x32\x0e.zproto.Entity\x12*\n\tdisappear\x18\x02 \x03(\x0b\x32\x17.zproto.DisappearEntity\x1aI\n\x11SyncToMeDeltaInfo\x12\x34\n\tDeltaInfo\x18\x01 \x01(\x0b\x32!.zproto.WorldNtf.AoiSyncToMeDeltab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent.utils.packet_capture.proto.world_ntf_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORLDNTF']._serialized_start=203
  _globals['_WORLDNTF']._serialized_end=772
  _globals['_WORLDNTF_AOISYNCDELTA']._serialized_start=215
  _globals['_WORLDNTF_AOISYNCDELTA']._serialized_end=311
  _globals['_WORLDNTF_AOISYNCTOMEDELTA']._serialized_start=313
  _globals['_WORLDNTF_AOISYNCTOMEDELTA']._serialized_end=428
  _globals['_WORLDNTF_SYNCCONTAINERDATA']._serialized_start=430
  _globals['_WORLDNTF_SYNCCONTAINERDATA']._serialized_end=488
  _globals['_WORLDNTF_SYNCCONTAINERDIRTYDATA']._serialized_start=490
  _globals['_WORLDNTF_SYNCCONTAINERDIRTYDATA']._serialized_end=529
  _globals['_WORLDNTF_SYNCNEARDELTAINFO']._serialized_start=531
  _globals['_WORLDNTF_SYNCNEARDELTAINFO']._serialized_end=601
  _globals['_WORLDNTF_SYNCNEARENTITIES']._serialized_start=603
  _globals['_WORLDNTF_SYNCNEARENTITIES']._serialized_end=697
  _globals['_WORLDNTF_SYNCTOMEDELTAINFO']._serialized_start=699
  _globals['_WORLDNTF_SYNCTOMEDELTAINFO']._serialized_end=772
# @@protoc_insertion_point(module_scope)
